apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-python-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: pipo02mix/my-python-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
