apiVersion: v1
kind: Service
metadata:
  name: my-python-service
  labels:
    app: pyhton
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: python
